[{if $oView->getClassName()=='start'}]
    [{if $oView->getBanners() && !empty($oView->getBanners())}]
        [{include file="widget/promoslider.tpl"}]
        [{*assign var=blHideBreadcrumb value=true*}]
    [{/if}]
[{/if}]